apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:z4QgIE+nkQn1YGUOYVpvxUWY1u6fVgk=,iv:T1/uuPMA7rng3x1YJTY79jdKSdXO1aT53fBXIrSt16k=,tag:cnlfeggAMTvRWZb8anpxxA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:PWXjGqgh21BWob1C2gRhTiTHATQIN+iKAAF8P7hFA96jkWh+qQ==,iv:drNaVtGSEUTSbNesi+Hg48sBTb6C4lrESsFiVK/Ymog=,tag:q5YmoEq9gD1+6F0jC7Dpow==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:l7045/mEyC7oyFzP0LcG,iv:OLnD/nxkDDUGjJpSfhASZEHSbi21xlFM5X4Wg93156M=,tag:Dm5DITAOxZF/HsRgM/FXmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qae6sg0atwrfa8e9nrjp7m2p929v8fcwc94em7wdr9urx7fyhd4smlmxv8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRk1UQ2pGVmVrZmRFTG02
            Y01sVnc4QVQxYXEyZi9YcStISDFVTGxpaUZjCmJWZjFCdXgrZ1hYTUQ4VU9IT0pz
            cDNCUkMyU2ZmbXVOcy9TMVNyVS81ZWsKLS0tIFMvSlZDNXZPMHk3MUhrdkVFMjJl
            MjFMdkN6b0w4WnV2RHN6Z1RqN0JDVjgKQZQpSbVisX0iB4tKLkWSLU169FLemiFQ
            2mmIrvQyYRJFaAta7h+M2Dj4Zi1gR+mNTjBMoNp+Wbbsagtg8XtCiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T20:29:51Z"
    mac: ENC[AES256_GCM,data:twdIzkLsj4Kp7XU7FHn2/jATZNK1I70+AF7bvohmVjk48QTTXiI1mF2Rzu/MX2NMQ/FfuYThhBqG1c1U6bGldKtfjWpdazoA/yTXjcoEzfjIKkh33F9M3O3RW6o7VSqDCqj/gfUAjZTJPpbfDD0O6s5YyZ4crcjKLAd1yNnzFTE=,iv:flwtvLbl9ShrJpcHDEmbA47HswBE0fQLVYsC8p0/Bmc=,tag:vwE4yeLQLCucqSpZAYOTGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
