---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: sonoff-zbdongle
spec:
  rules:
    - # SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P
      name: sonoff-zbdongle
      labels:
        sonoff.feature.node.kubernetes.io/zbdongle: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: { op: In, value: ["10c4"] }
            device: { op: In, value: ["ea60"] }
