apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
stringData:
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:NTHSLmTAumY//P4vsYRbCpKGAWKuGA63gfE=,iv:d9Z8p+UpN80CJjKkBcsWKMWZT08jsjRppcYNB0C7OcA=,tag:2Rd2m5+iu5Nc7OoeG7ql2g==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:AR/yfmA=,iv:Q/H5KCROzPyKiHbo0yiVZVSqyNNGu8WpBfp4tU5OsYg=,tag:FymXETKWJV2o2iA2b4VFAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lyp35zxv3440rp2d23fyhhfjs2qxgrqzmpp7w7avm4h59mujmgrq87yeza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRENPWmlvQVA5R0ZZUGVX
            WUZXajVyYjlmV1Q4b1RkcHNIdVk0UStpeVJjCkxSaXRHVzJsaGRkZnpWVDB1aENy
            c0JFbytDZlBTTnN0Nms3MFhDV0dZNE0KLS0tIDRaUVBSVzB4SkpRcHMzM0JneWcr
            R3JXRlpISTIwRGszdXVIL2s4R1Z6SkUK7uBdncyA/G9G30AkctnNPkUvCtTvf+1N
            CZxBNewa2sQIESwdX23Ro05wYSHYDN67B/fyD2H6xb7Fo0GdvYgNtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T16:10:22Z"
    mac: ENC[AES256_GCM,data:7tLuHvdkpxvK4uafD+SADaROvucUsBfYE1hjXCMc98b3P8VggNe05uyB8J8ae85ovaKFvXTJvfgQg/5bTILKHkL7l3KwdeTlHKAV8+3pc+M23uofkpY/DZ05q+ApI1m0vwrZnffEz1dMUIrFjgMJvjYTDoT9uAeGWH8zd9odSSo=,iv:CqZgus7jdkKuRkLUezYEJUx8VeKpWFeemI9Z+nXQNog=,tag:vnevMbxcAYEOdrQZOjLe8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
