apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:vPZS6AQU9NBsC30dorgi82tf9K0O7XktvZ2r0UyWRCy8euoM5y0mdg==,iv:sowZePEzh7uJHkW+3TvJEL/FVUFUi+PHcT/Gtu0XQu8=,tag:uIcnJlNxahvIF+j/E6Ln3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qae6sg0atwrfa8e9nrjp7m2p929v8fcwc94em7wdr9urx7fyhd4smlmxv8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYWc1d3BKMjEwSXRibFF6
            YUV6YUJPQVNjaCtMTHBXWnNZZFFhVTFqL2dRClgzMG5DNFZmVkphc0Roa1ZlRWFL
            L3dtaHNXbHg1b3RNR3RXNHF3WWtzdjQKLS0tIGViSEdwWEZSc25mZkwzMHRaN3Y3
            Ly9KZEMxM01BdE9XS1lhcDBqZWFZUTAKdW00FJLuL3+N/EEQo8ILuk4GJVYtBfnQ
            ws758afnmBB2jHo7gkfquy4fgWoJK8uiLTuMMfOTWU4aK7/0PnWWIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-19T11:51:13Z"
    mac: ENC[AES256_GCM,data:uD2oBPB0ozXelLQzw47Ml7HsE9knahz3RfcScqLERTGzzOFIRIwBHJOxx0chyF3I7m+LzsAmZ1OeMuxFDRVYAqA1kapeEAEdmcmgENolt3Ai2nPY6drgRV1I2wxzORiVyNlCFcAAD5sjsET97U/dD/6Njhze5BMfI3clo5cN+nk=,iv:3aWIe1MSCIPTDQVRdlDawz2DIVHoSBZuV8qRVJSQ02Y=,tag:jaU7zrP7eEIJHAg+3irA3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
