apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:U9t0bOyU9NACPxzvy+Ppe1CiKf6A/lbR5J3OfRP161E6LCJka8U5tA==,iv:GY7dKZdC8NQY7SfpMX4Rm0WjYO6efAoMDVR09i3QyXo=,tag:bykzcEWGI8cH5b0EfacUUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qae6sg0atwrfa8e9nrjp7m2p929v8fcwc94em7wdr9urx7fyhd4smlmxv8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbHhpdUJlcGZHb1AxU3Qv
            aFVDQ2pIa2FMUEdqU1pDZFFsRVJzRk01R3h3ClNIbFpBcmhmZVNUK0cyZTViTVhI
            OHBVOU9Rd1dNelo3bThiODZxRjlQalkKLS0tIEJra3B3eWpGajRobEVQbGtUQVdy
            R0NwcldLL3Y3YittOTZZTVhBZG1GTmMK6SDpbbkQb0zlBfZRP1hGOgfG84gdtu+2
            b/Xt2mPDAT9sNGQKTUlWjWAaMrgr6CndExDIKQFEVXkYWilA7zoYhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T20:29:51Z"
    mac: ENC[AES256_GCM,data:VOCc7tY8vq0PqZB7z0Ts8hdYhTwYLu06t78nq+MS0wMmSx4Wf+m+rvpMxo3BATBATjLpzczw8LdR2tXHRDGrxdkTAy2rRIpvebXOOZOswaL50lOksXvt4WMhi0xxpmFpcrgHXQ59sKiecZG1bLe6nqYpYV1okmPRn/qtXSfhpTI=,iv:PjYNE3C5xr6wHufQlY6Zr7MsPBs1T5p7nifcE/LIv+M=,tag:Ehm65lqgbx01Vu3n1zW8Kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
