---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname paperless-redis
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/default/paperless/redis"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
