apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:uK1nhNi5glgGqkes07MDbRzfCn39G/4/PEV83V/REg5bodvuJA==,iv:f3AMvZ612jBI+Moo0GMvZbUU7X41yVddkyGBiHmxr10=,tag:nOAe9Tu2kA2twWSupfoMVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qae6sg0atwrfa8e9nrjp7m2p929v8fcwc94em7wdr9urx7fyhd4smlmxv8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcmNJdEJYdXZSN1J6T1Yz
            cGxoa29KY3dyaDBRSEZzSE9HTFZ4cDdIekhBCjhHN1liL2RRMmNlZmc0dTZ0TUJ2
            Q2F2Rm5CNkJzN3Fjc3VUejB6bi80WUkKLS0tIHV1RERRRzR1eVFia3ROdDQ1ejh4
            NzJxY1grZW1TZmU3MzBXQU9QRUFFazgKiuw6QWxpG4wToJwYqJbOwUMrp8hbP3Ln
            VI4b56IMURBP3hqWyJbNrVcTfEO1m9zt0ioce0xD4qgSZzr+DdBT+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T20:29:50Z"
    mac: ENC[AES256_GCM,data:6AQnxo46hx/oGwlMHcEZ/7CDpikvuP/xleDu5brlufRsW53yvzXBsMC5BaW1GgMF4hH2F7zyQrtlzC7tchsx03s/Ug6OKI3+XGdpXJuaUjlLtMu1e83pHF5Kzc9OXnjqv2GimA2V+ue95wLmMcwqrujkYmW4k1OpFKL0weWiGRY=,iv:JTARrnsIwHB3p02U2UBBbBH2277GFfevX+FlHqTMVWk=,tag:Ivm6HRLVgW6yfq5TC03P3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
