apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:m7BWdPBrvsp82lZW0ng7NrMhZmkCw3o=,iv:goxm5UWByGBD3G9Ttb/7zr8LRsWl2cDWKMJ7cB5pITw=,tag:kezY86j8ZD3r6QPtKRRy+A==,type:str]
    api-key: ENC[AES256_GCM,data:2ya6Up9xad5JKywKCQtzQmwG9K8BwXiTDaFUOGfz0TbmXLVgqw==,iv:ibqiFz03PIU2+SQB+YFiix9h+Izm/Hf0+blLwwfh+fw=,tag:Q9gG16dacARTPV7NK6x/sA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qae6sg0atwrfa8e9nrjp7m2p929v8fcwc94em7wdr9urx7fyhd4smlmxv8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QXdNL0NYM3BrVzlKcEp1
            ZHZodUtEcnEwOEFWdEtvbVEweXlHQWliZldRCm9ockpIMGY3dnE3QmR3Y29zN2dh
            STdWTW9EZ01ldzh3MHJMQUd4MnhPNk0KLS0tIFpocDhrblUyTktKQkhSTSs1cFln
            dkZwZm1NV09XRXk1d3I5bWRzMmZVQjgK9Ngf29hw5/29w1UA5MGOOT1atiK/mCzn
            myCbP33tlLH0wl3xElO6/fGnjOX53ZU7UpTLBG33z9MupUe+mS7rLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T20:29:51Z"
    mac: ENC[AES256_GCM,data:pDuYpxs8BNHbN0xL6EioJpXsfphZsvc2p1Qe238oeP31rpSWCMOiqPvFB5040EE4J0tKiUxNR5vdPTOAFyX0JZQhjO0rhugBX24zUvk7Yru2TUHzAatfLfH/1bLHW0StUhrzzdtfHcxuDjIKcDyur+lpQl8TIScl5T4zl3NXeqk=,iv:mEijeCeinsZtsicc2ea+rZLZ7WBNneZmDQ/8pgDbSFo=,tag:VwlusxSOxZdaLZEt8eWuTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
