---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./home-assistant/ks.yaml
  - ./homepage/ks.yaml
  # - ./mealie/ks.yaml
  - ./mosquitto/ks.yaml
  - ./zigbee2mqtt/ks.yaml
