apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whisper
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: true
      enableServiceLinks: true
    controllers:
      main:
        strategy: RollingUpdate
        rollingUpdate:
          unavailable: 0
        containers:
          main:
            image:
              repository: rhasspy/wyoming-whisper
              tag: 1.0.0
            args:
            - --model
            - small
            - --language
            - en
            probes:
              startup:
                spec:
                  failureThreshold: 90
            resources:
              requests:
                cpu: 500m
                memory: 250Mi
              limits:
                memory: 2500Mi
    service:
      main:
        ports:
          http:
            enabled: false
            primary: false
          whisper:
            enabled: true
            primary: true
            port: 10300
            protocol: TCP
    persistence:
      config:
        enabled: false
      data:
        enabled: true
        storageClass: longhorn
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 8Gi
