apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:t44FZyCQ4NBEo1QGqriBAzPRAptfmS8GIMzegDfjvdXadm3YGPNebfJI4NAPG5MQkm7VqU4gc8edWzls,iv:XT/QSbmOqG2cMAUAhidu+JEo4VSxUWSwlPi2kcFnbnQ=,tag:yuOrJAW6eC6MBLeyEdxkyw==,type:str]
    username: ENC[AES256_GCM,data:BWfgNQU=,iv:C78S2I3R/q9mWSKXcteCw8qSHqissG6rweCy5Jj6CIo=,tag:T8rE4WWbvPVyWFXx6eSk2Q==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lyp35zxv3440rp2d23fyhhfjs2qxgrqzmpp7w7avm4h59mujmgrq87yeza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R0J3Y3NGemtmK053ajhu
            aUlJLzFabm10bnRKVW5QWnZxWmY3TUs4aFZVCitBdVo2R2VkRXdLTTdUWm1WeFRH
            dzdJU0JOdml6aHJDaXcrSC8ydk1xa2cKLS0tIFZmWUlqbXJaM2VlSGJyZGhETkFU
            TUQwNnY2aFBITFI0bjVEc2Y4alZERlkKcMDPz2DHmzryxXtrWcrjgFnxMMB9osgu
            FeSlbq+ClevWDfnA2O3SUlMBmKwO9tlMvgocrPs7iXPi+EXExQEA7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T17:58:05Z"
    mac: ENC[AES256_GCM,data:rx00nUZRdQgCEPsZ8CAbc4XqETDVFgy5mN3W4m0RRSpnT8ariFfUACuY00nSDhuC5Yk8TYGBFeZDmlDjaxscsJ51yXMfNlmuMZwdmA/+ycnleIbT31V6h3xp3x6+O9xmRy2gf0oT6Bc/EPwjEd9PFyYqz1WTEo6pyIyB7ISEC/Y=,iv:2KBQZApCywkROJZkUIufgg2q8d9uWCcW+Xy3id8795w=,tag:XGAZKwr4Cl5jt8xI7+/8VQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
