apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:TpTLX3mi6iQ49xII45po1hvecJexF9oTuMFYw/gCr/uSC6rgLxpEogKS2f/sBfWNs8F6Zx1V+fnNERQW,iv:u5o2+2i5P1I1/BbXBYmsCFgt2MPAkdSZm/yzua1E8Ic=,tag:lC3ebLzN8WNSeYq335GHIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qae6sg0atwrfa8e9nrjp7m2p929v8fcwc94em7wdr9urx7fyhd4smlmxv8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb1F3b1ZMdjRGa3ZaOTBE
            dFJBTWJodEt5a1gwWFQ0NytkOFdwWENhL1gwCkFFL3VyT0t1YzF3T010eDg5emVk
            TlZEdXJBRnVmOXhaSnBUb3hFSUFuNmcKLS0tIG02SndpL1dRYTdrVEEvYm1TK3RT
            dVBzR0xJa05NZkF6RGNxQUQzRzdjN1EKpw0rDmnzmQRKNMZqOKg6B967EVPIkRbU
            TcOX+oo55hnOzNeCXsO2eOl09C+uf0bQW7yzCDFeZ+UQIvt722cVHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-19T11:51:14Z"
    mac: ENC[AES256_GCM,data:lSwJyg2XEcwewTJoprvJTMUlz4s3tzDe2k2HYRjh1waX2R38z0nramSpQzQPCrcLqKkyDX5nPyJToXOpdAyqLDVEzWdcg4E4mYUiBBG7dK3H7Km8riDi89VM2jO2PGCLA4Fs8kc+99vSG3h+RCUDo1NCNxdTFAKkA2g41frtIbg=,iv:HInRCAR3RWZOnKjKLuO03Q2KrCJNjiqJcBarxRJ4Gzk=,tag:hNh74Hslmd+3e4IdpNUanQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
