apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:pB7zTOw2IL2fxRNw+VuUkUZwmRokh/eXZ3qc218oyRICOs6lKmhvupzq2taa8GYn27RTsc+Evj+WOKMe,iv:gOYoEVitubEoVsHj5o/rG7gXBhA0TwEjzboNVdYg8fQ=,tag:LMW5K/9LirbiSUFBjXNENw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qae6sg0atwrfa8e9nrjp7m2p929v8fcwc94em7wdr9urx7fyhd4smlmxv8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiamx1MDNTQitTbHBWdS8y
            cHpsYm9nOEc5eGgwTXR6M3RCLzlNSlFUU1EwCjhBTC9sUFQyMEo3RXorc0s1WS9U
            TDVwZ1RiTUFjMTZwa081emR4KzhOTUUKLS0tIHlTL2NrQ3JpZkxZSVlNa2x5WGNq
            RXhMOTVVaW1XZUdqV1g5d0I1MkN0MDgKcH9/P0+0CYmUdueFCEqkkQ8KtwF54RJX
            vbztS/Ldy8ZeD5O88/5GK4vpUwNt/OwkOBgli3dcBAHGhLcLJOXCEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T20:29:51Z"
    mac: ENC[AES256_GCM,data:qBBPTXomV+uC8PElRHGuFfAxbeM5ruYxrIRZS/C0b2tSGl2hFw53olD7oroq0M9AnwksnD9UR80xNVQtLDLiEuUAR0ArLRufuMxQa+JrS+Q3QZ5nu95QTssF0HEMmk7tlZl3IT85p47kyF6PSk+0HUcC9iUvePlnC1XsReLf6f8=,iv:XUulNRd8ItI10LHhFW+nrqTwViJHs/sugie/JmiBA2I=,tag:ibU4nexjzjdFlFPagyt1jA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
