apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:AEJ4pNZIDcx5GQ==,iv:q+1Z5+GPg9/mK6S7rKbxbCIWI4I6T5setCjCzynCKL8=,tag:41yO9r00GUfu/N4LFeQ/5A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:I9iNeUwIdkZRif/bx8lsrlq2eoM0EEk=,iv:2f53c0xCXsEY3u2e3cNnz6FoFvi9ruNm6NL8W19CVPM=,tag:yrU9rdGtOce58IXP+9yd0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qae6sg0atwrfa8e9nrjp7m2p929v8fcwc94em7wdr9urx7fyhd4smlmxv8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT0cxK0ExTnFMRytTZWRG
            U0ZmYnBUTzVQTnRnTHF6czA2UGx0NUVOR3ljCkFDNVl0ZUNsVGwvU2xMV1FVaFAx
            S3RmOU5Md0ZicERFdUhuY25ZRk5TNmcKLS0tIGUyQUNmbDRzTlU3R1ZaYTVXRGhL
            K2NadDlERjhmMGlid21nWEsvN3duRG8KYnf6XtvOdHQ6zzFPc8803n0nWRJ8CiL8
            9JltqCX+swN8FCiue8EL7AsrPs4vOL9ejZ/6HMAL/pP08re4rh58FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T20:29:50Z"
    mac: ENC[AES256_GCM,data:euuhTT8qm41z6TSMh2E9Lzneu8HmbNvRTk9NFRCI3lKBhzo0hZAbxpqxhSG6lH7pOqWFp+7TvcwojlOkv4y6jxNjvoE++1eHLu2OXqtweuD6xBHReBvULNjYZxChp2YtUeggufvkx8GEgMq6JiOzQyZ/z/1LEA/saldHR0b04y0=,iv:DFfEDwJsrNqPiSDH2ibmQnTgKiNfjB6PJs9QtGEfaF4=,tag:tu3Mbb/cp931tAbihiapQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
