apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:AzGggGau2z6sPBx3,iv:LDPbHNMrI7JX6NUlG0VCRgYQhcRy6hm5PrTTi67BWSA=,tag:t1OOJhlmkHEPrFyoyvq9rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lyp35zxv3440rp2d23fyhhfjs2qxgrqzmpp7w7avm4h59mujmgrq87yeza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUXd3eGJXbE1NY0VTV2F6
            MTE4NzlUdEEvdlBUUmt2UDU2ekkxenVreFNBCkpxU0pTVUFmS1ZtSldMZ2VYQk9D
            MG52LzJMa0JzZjBFK2hBYjQ5cVlsbVEKLS0tICtMSG5weGQxVTBWRFJrcXE2UTlE
            QnlnZnJjZllVaEJBSXI0b092VnZsb3MKKrE31K4K4tICjF8N/+G14nkas7AAmLju
            tYKw+9/RahK4OhbiDv4YlPrmI7jUJALx47hef2IqA/iUjiAoP6z96w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T17:57:55Z"
    mac: ENC[AES256_GCM,data:azDNaE3+V1ySb5pBVdwi7DfPC10tRzPrlDFq8Xu3H2Sxs6SVjmu1w24yYi5qDQOzK0ijVg6i9l1G8P3fgzkdJYlBUKJv5zVDaq9fB0jXTCAzEZ/2fxQbfE1AR9DUboMR5ODbV0leiUKsZLVd7eIjAJGEY0cg7FUvuT7qucT0Mbw=,iv:/wQ/ZBbBbS8e0AjVb2whmpGvk/J5c6nb/5p9Zn6pRvU=,tag:2IBL8d0XyAqQ95lN6KwyXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
