apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sfZZtPZYktLbZ9VlxoNzt2zWkpk4wg==,iv:+GSYw+IWyMzcNPE5bJNB7Rfz9vtzy6YqE3AgEj8RTno=,tag:v1kiICrtTpMg+o9gEp1eBg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:kia4xX7Rel7WlUWGm2C6JrA2CRAucoq9sZ7atAeElQ7VPE5D,iv:uuJASnkkqoGGHPSEB9Yk/NK52XJbcz2dHJmuCUHKr10=,tag:I2U9kIL1jbUJzwwof1Ct5w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:sP/kxZri8r3xGg==,iv:w6GvFOQ24tEd4CuqPY3qnbf23nFwyQ9rvb9ttOr8xgg=,tag:azVouFZFrU8S2HKVGN/Ckg==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:VE8dwK533VN3A/2Q1g==,iv:1lGF6fZaYikeapXkkbkfOB3HTYGtsNPbUANcy/cUiu4=,tag:3wabjAaDTGmz025V2WZ9UQ==,type:str]
    SVC_HOME_ASSISTANT_ADDR: ENC[AES256_GCM,data:JLfwgfwd8gd6neqO/w==,iv:nU3P/UDwQfo59uW7MVUYNM78DTN+G76QL31asaf4B94=,tag:hMMqlAqxo7EvGPdFjAzGqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lyp35zxv3440rp2d23fyhhfjs2qxgrqzmpp7w7avm4h59mujmgrq87yeza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb0pBSkhxZTNidEtQaDBz
            eE1MWlZ2aXFaSVlEN0RiTkU4eTd2MW5GaVZ3CnRNZVBtUE4rdGZVbUZQRWxTV3Vn
            M0IvL1d2TjVPeHBFYW4xbHVuZE9CMGcKLS0tIHAyVHkzWnh6V1lUOUNrcmRJaEY5
            Q0FpcGNpQmVqdHBjYUVNR0QxL1o2VDgKv5hQ4mMvrW+qvN1m6X45tSTZEQCRqJVR
            eXGgSI154ebkHIK4gHPGBLMkRXrrEAAGgs5L6nS1TaO0dwB96FjQug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-23T08:48:20Z"
    mac: ENC[AES256_GCM,data:/Ttoja6Q1aLrxuITgvN/NWH9kt6V63StnvUlBR8Mxm4udNRE+4cgVUanbGX7tUF5TgqMJFKGxzFInbelVPm3CVmq9OBXRc4bobRfg74lDAQmkVFpMUKxQbynXRGRwm13wG1eoBeG8E7g/mKP2PP1niFMEsXW+bGMfOJfLSFOEQU=,iv:TtYrhGH9wqWgy4UwWokrEBpo8comuZgax70Wet0V1J4=,tag:zAH0A9rmHwdSiK+6c6/bKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
