---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres16
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-19
  primaryUpdateStrategy: unsupervised
  storage:
    size: 8Gi
    storageClass: openebs-hostpath
  enableSuperuserAccess: true
  superuserSecret:
    name: postgres16-superuser
  monitoring:
    enablePodMonitor: true
  managed:
    roles:
    - name: paperless
      ensure: present
      createdb: true
      login: true
      superuser: false
      passwordSecret:
        name: postgres16-paperless-appuser
