apiVersion: v1
kind: Secret
metadata:
    name: postgres16-superuser
stringData:
    username: ENC[AES256_GCM,data:M/cdldRKlRA=,iv:Z6VLB5wxD5pZ7wAvO/n2r3XAay4cmiW8fHP9srVaUOg=,tag:lCi5/1iJaMn8dLHAhXZxKw==,type:str]
    password: ENC[AES256_GCM,data:KqIHNv9y3b6Hm/xOSxo=,iv:U0m8PM/nB29310js5SQKAgmDW3XuNVZ2yQ2H62GfYM8=,tag:tHvaSU9pD0JTPjcXdHIR0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lyp35zxv3440rp2d23fyhhfjs2qxgrqzmpp7w7avm4h59mujmgrq87yeza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUk1iQ3pkYzF6bDZJTGEy
            dVA4andCYmlvYnZBNk95WkVnTlRnYnRETjFNCnlPZGhXNmt1eVBQVnBoTitGei9k
            dElKQTBtUUZWNWNWd2g0em9LVmRJK1EKLS0tIHhGRExXYVlvTFJtTFBOQjJodjdZ
            OXFLaER6RDBTMm9kUXN0U3dZeEsyejQKzPyI8IEKt70y0DYjX6yW6Ile4ofDMpCv
            9XzpQxG18iI5vDO7KHl9YCgEYR4AdSOhwg1zC+aUoXFcgK2o3ej06A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-10T21:16:48Z"
    mac: ENC[AES256_GCM,data:v1RZJlJ8X2iXZnhZkOWpbI7UmChJiaP7faS6ZUN4DOsH15OfWOMdNxEBZn3V92pcVv6BbPbEhSSsmPU3StyimbFUs1MzlBSws/yTUQ3kAc4fskhtQijIwJtrV2tVoG7MbqnyNX5yuWUo7HTrS1yRiijkCdurAzECJtCn2Tqb16s=,iv:NyaUGM+7U8WaeFn6KBKqzJTn1nCdCChiDFYagiazqao=,tag:OHnG1uAhDGFenPZ+rEaW+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
