---
apiVersion: v1
kind: Service
metadata:
  name: postgres16-loadbalancer
  namespace: databases
  labels:
    cnpg.io/cluster: postgres16
  annotations:
    io.cilium/lb-ipam-ips: ${SVC_PG16_ADDR}
spec:
  ports:
    - protocol: TCP
      port: 5432
  selector:
    cnpg.io/cluster: postgres16
    role: primary
  type: LoadBalancer
