---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: default
  labels:
    app.kubernetes.io/name: paperless
data:
  TZ: "${TIMEZONE}"

  # Required services
  PAPERLESS_REDIS: "redis://paperless-redis.default.svc.cluster.local:6379"
  PAPERLESS_DBENGINE: postgresql
  PAPERLESS_DBHOST: postgres16-rw.database.svc.cluster.local

  # Hosting and security
  PAPERLESS_URL: "https://paperless.${SECRET_DOMAIN}"

  # OCR settings
  PAPERLESS_OCR_SKIP_ARCHIVE_FILE: with_text
  PAPERLESS_OCR_DESKEW: 'false'

  # Consumer settings
  PAPERLESS_CONSUMER_ENABLE_BARCODES: true # enable search for barcodes
  PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: true # enable setting ASN by ASN barcodes
  PAPERLESS_CONSUMER_BARCODE_SCANNER: ZXING # switch from pyzbar to zxing for better recognition

  # Software tweaks
  PAPERLESS_TIME_ZONE: "${TIMEZONE}"
  PAPERLESS_TASK_WORKERS: '2'
  PAPERLESS_THREADS_PER_WORKER: '1'

  # Docker-specific options
  PAPERLESS_PORT: '8000'
  USERMAP_UID: '1001'
  USERMAP_GID: '1001'
