---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: Secret
      name: longhorn-config-secret
      valuesKey: BACKUP_TARGET
      targetPath: defaultSettings.backupTarget
  values:
    ingress:
      enabled: true
      className: internal
      host: longhorn.${SECRET_DOMAIN}
      tls: true
    defaultSettings:
      backupTargetCredentialSecret: longhorn-backup-secret
    monitoring:
      enabled: true
      createPrometheusRules: true
