---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
spec:
  name: "backup-daily"
  cron: "0 6 * * *"
  task: "backup"
  retain: 2
  concurrency: 1
  groups:
    - dailybackup
