---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mealie
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    timeout: 25m
    remediation:
      retries: 3
  upgrade:
    timeout: 25m
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v1.0.0
            env:
              BASE_URL: https://mealie.${SECRET_DOMAIN}
              ALLOW_SIGNUP: true
              API_DOCS: false
              DB_ENGINE: sqlite
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                cpu: 200m
                memory: 800Mi
    service:
      main:
        ports:
          http:
            port: 9000
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "mealie.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: mealie-data
        globalMounts:
          - path: /app/data
