---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Media:
        - YouTube:
            - icon: youtube.png
              href: https://youtube.com/feed/subscriptions
    - Git:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: https://kubesearch.dev
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Network:
        - Cloudflared:
            href: https://dash.cloudflare.com
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel
            widget:
              type: cloudflared
              accountid: "{{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}"
              tunnelid: "{{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}"
              key: "{{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}"
        - PiHole:
            href: "{{HOMEPAGE_VAR_PIHOLE_URL}}/admin"
            icon: pi-hole.png
            description: Pi-Hole DNS and network Ad-Blocker
            widget:
              type: pihole
              url: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
              key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}"
  settings.yaml: |
    title: Dashboard
    theme: dark
    color: slate
    headerStyle: clean
    layout:
      Home:
        style: column
        icon: mdi-home-analytics
      Network:
        style: row
        columns: 3
        icon: mdi-server
      Observability:
        style: column
        icon: mdi-chart-line
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: ["duckduckgo"]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Welcome!"
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
