apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:9GWt5MTfM7K5BmB4LOCKmt0aj3VBR+c3ErKkccWz8Cc=,iv:DN9m/g20Tz2cJ9paUQQ52IG+GqaiTq2CldJpLkzs3XY=,tag:KQt3kThkNlfzzUb0DU5DqA==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:CzdKRQBpDq60HIegKPy4EyvBL+1v9acmb/J1MXyqTfQZ7ioOWhs2fg==,iv:mv3+kUIHAEL0Fr4QYVryOhmn2k/lDzVDfc5h/AX+Hh4=,tag:+cNrRRm5PPoeIIW5s84Y0g==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:b1HxEwSoaN5gWV8Zl1QooJZFDezXS2Uv62Z96g4znBE8dZzB,iv:oywhDLPOPpDZnLS0F+tGACAUt/5rI5vwU6mv/KjgPQc=,tag:cHaAMsNHn4BiU4H+pMfdHA==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:Ku4FGYi5p5/vdGUO,iv:l9pF5X6Oujtv737oL1KjIlnCdiPCWDt9ePZZ/E58Sd8=,tag:qLv+Ikzf5w+K1A7kigu1qg==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:jEtTRQc=,iv:mSWURXV0+zQMoI2J1aKYdh9BpPK1r+ZCem6lsGMyTic=,tag:T4XVOtrPodNjO8dw/RrkYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lyp35zxv3440rp2d23fyhhfjs2qxgrqzmpp7w7avm4h59mujmgrq87yeza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SW53dlhBZ3ZRQkJMcDhr
            Q25WaGoxeEMyZUtNTmdhYS8zckZSSlZBYncwCjNjelovQ2JCNy9kN3lnaEhOWDRF
            SWNsaU9hWEV2cThmcEJSaG5JWk1MaEEKLS0tIFZXc0ZOaUh0Q09ERk0zWXdUYU1H
            WVhXdU9mVjJQKzVneEttV0Rib0FRRmcKLIXn2N6xLptW6+mI4rmtAWqBj0GE2tZl
            A5CB3fxZII3dHu6tq1ldUu96KozDMeYbiZCUyj70Fu80jTP1ULULxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T14:48:10Z"
    mac: ENC[AES256_GCM,data:o8Y8/0Yhx4oXdig4Zjqn/eNsa30g6b22BmxYemTRqaTPyaG3+qi/YP4VUFmSLQDqLc8kAZXdOpNO251rv7VhbpCMvAGC4ZdeSQzPMxS41RpRygOPhsqQmRQzX/wqz/TjmFWxZ72iRCmESmWgME2SILVN2ODhv+i7vwtnUuQLgt4=,iv:Pfu9FBP4pEo6viSJfp5VcHOXB7G1lfmsPvUVuQRpzT0=,tag:+UrbAVkQ+iuKk9BO9OiEaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
