---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.1.5@sha256:825cc0170b607f518e669400237cf3d777dd86799028ae97a97e8f2f3e51615a
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 400Mi
              limits:
                memory: 700Mi
          codeserver:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.20.1
            env:
              TZ: ${TIMEZONE}
            args:
              - "/config"
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
            volumeMounts:
            - name: config
              mountPath: /config
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "${SVC_HOME_ASSISTANT_ADDR}"
        ports:
          http:
            port: 8123
      codeserver:
        type: ClusterIP
        controller: main
        ports:
          http:
            enabled: true
            port: 8080
    ingress:
      main:
        enabled: false
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "hass.${SECRET_DOMAIN}"
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
      codeserver:
        enabled: true
        className: internal
        hosts:
          - host: &host hass-code.${SECRET_DOMAIN}
            paths:
            - path: /
              service:
                name: codeserver
                port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
