---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/dailybackup: enabled
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
