apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: piper
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: true
      enableServiceLinks: true
    controllers:
      main:
        strategy: RollingUpdate
        rollingUpdate:
          unavailable: 0
        containers:
          main:
            image:
              repository: rhasspy/wyoming-piper
              tag: 1.5.0
            args:
            - --voice
            - en-gb-southern_english_female-low
    service:
      main:
        ports:
          http:
            port: 10200
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /data
